<?php

namespace App\Http\Controllers;

use App\Models\Photo;
use App\Models\Review;

class HomeController extends Controller
{
    public function index()
    {
        $dbPhotos  = Photo::where('is_active', true)->orderBy('sort_order')->get();
        $allPhotos = $dbPhotos->map(fn($p) => ['/images/house/' . $p->filename, $p->alt])->toArray();

        return view('welcome', [
            'allPhotos'  => $allPhotos,
            'photoCount' => count($allPhotos),
            'extraCount' => count($allPhotos) - 5,
            'reviews'    => self::mergedReviews(),
        ]);
    }

    public function allReviews()
    {
        return view('recensioni', ['reviews' => self::mergedReviews()]);
    }

    private static function mergedReviews(): array
    {
        return array_merge(self::dbReviews(), self::reviewsData());
    }

    private static function dbReviews(): array
    {
        $locale = app()->getLocale();
        $monthsByLocale = [
            'it' => ['gennaio','febbraio','marzo','aprile','maggio','giugno','luglio','agosto','settembre','ottobre','novembre','dicembre'],
            'en' => ['January','February','March','April','May','June','July','August','September','October','November','December'],
            'fr' => ['janvier','février','mars','avril','mai','juin','juillet','août','septembre','octobre','novembre','décembre'],
            'es' => ['enero','febrero','marzo','abril','mayo','junio','julio','agosto','septiembre','octubre','noviembre','diciembre'],
            'de' => ['Januar','Februar','März','April','Mai','Juni','Juli','August','September','Oktober','November','Dezember'],
        ];
        $months = $monthsByLocale[$locale] ?? $monthsByLocale['it'];

        $guestLabel = match ($locale) {
            'en'    => 'Verified guest',
            'fr'    => 'Client vérifié',
            'es'    => 'Huésped verificado',
            'de'    => 'Verifizierter Gast',
            default => 'Ospite verificato',
        };

        $badges = [
            5 => '#2E5E32',
            4 => '#3B82F6',
            3 => '#F59E0B',
            2 => '#EF4444',
            1 => '#EF4444',
        ];

        try {
            $approved = Review::where('is_approved', true)
                ->whereNotNull('email_verified_at')
                ->orderByDesc('created_at')
                ->get();
        } catch (\Throwable $e) {
            return [];
        }

        return $approved->map(function ($r) use ($months, $guestLabel, $badges) {
            $rating = max(1, min(5, (int) $r->rating));
            $stars  = str_repeat('★', $rating);
            $score  = (string) ($rating * 2);
            $first  = mb_substr($r->name, 0, 1);
            $last   = $r->surname ? mb_substr($r->surname, 0, 1) : '';
            $name   = $r->name . ($r->surname ? ' ' . mb_substr($r->surname, 0, 1) . '.' : '');
            $date   = ucfirst($months[(int) $r->created_at->format('n') - 1]) . ' ' . $r->created_at->format('Y');

            return [
                $name,
                $guestLabel,
                mb_strtoupper($first . $last),
                $score,
                $stars,
                'myhouse.it',
                $date,
                $r->text,
                $badges[$rating] ?? '#2E5E32',
            ];
        })->toArray();
    }

    // [0]nome [1]luogo [2]iniziali [3]score [4]stelle [5]piattaforma [6]data [7]testo [8]colore badge
    private static function reviewsData(): array
    {
        return [

            // ════════════════════════════════════════
            //  SCORE 10 — Booking.com
            // ════════════════════════════════════════
            ['Marco',       'Italia 🇮🇹',      'M',  '10', '★★★★★', 'Booking.com', 'Maggio 2025',
             'L\'appartamento è graziosissimo, pulitissimo, curato in ogni dettaglio dal proprietario con grande gusto. La posizione è perfetta per visitare tutti i principali punti di interesse della città. Inoltre la disponibilità e la gentilezza del proprietario sono un plus di cui tenere conto.',
             '#2E5E32'],
            ['Katie',       'Irlanda 🇮🇪',     'Ka', '10', '★★★★★', 'Booking.com', 'Luglio 2025',
             'I had an amazing stay! The host was incredibly friendly and welcoming — they went above and beyond. The apartment itself was spotless, well-equipped, and had everything you could possibly need. The location is perfect — right in the heart of the city, close to all the main sights, restaurants, and shops.',
             '#2E5E32'],
            ['Davide',      'Italia 🇮🇹',      'D',  '10', '★★★★★', 'Booking.com', 'Maggio 2025',
             'Posizionato nell\'antico quartiere Kalsa di Palermo, l\'appartamento è delizioso. Arredato con gusto, molto pulito, fornito di ogni confort. Maurizio è stato molto premuroso, prodigandosi in consigli senza risultare mai invadente. La chicca è un delizioso terrazzino dove godersi un aperitivo.',
             '#2E5E32'],
            ['Caroline',    'Irlanda 🇮🇪',     'C',  '10', '★★★★★', 'Booking.com', 'Luglio 2025',
             'Maurizio was a fantastic host. A wonderful warm welcome. Genuinely passionate about his city and ensuring guests enjoy every minute. His beautiful apartment is very quirky and feels like home. Fully equipped with everything needed. Lovely terrace an added bonus. Very quiet neighbourhood even though it\'s close to the centre of everything.',
             '#2E5E32'],
            ['Lucy',        'Regno Unito 🇬🇧', 'L',  '10', '★★★★★', 'Booking.com', 'Ottobre 2025',
             'Maurizio was a wonderful friendly and informative host. The apartment is tastefully furnished with a mix of vintage and modern items. The charming little terrace with its flowers and plants is a little oasis of calm in the middle of the city.',
             '#2E5E32'],
            ['Roberta',     'Italia 🇮🇹',      'R',  '10', '★★★★★', 'Booking.com', 'Agosto 2023',
             'La casa è stata veramente una sorpresa! Le aspettative hanno superato la realtà delle foto! Completa di tutto e di più, pulitissima, con tutti i confort e arredata in modo delizioso! Maurizio è una persona deliziosa, pronta ad accoglierti e attenta nel seguire il tuo soggiorno. Sicuramente torneremo!',
             '#2E5E32'],
            ['Wester',      'Belgio 🇧🇪',      'W',  '10', '★★★★★', 'Booking.com', 'Giugno 2025',
             'The Host was very helpful! And the apartment was great, clean, very cozy and nicely decorated. The location was very good, with lots of good places to eat and drink close by.',
             '#2E5E32'],
            ['Natalia',     'Polonia 🇵🇱',     'N',  '10', '★★★★★', 'Booking.com', 'Giugno 2025',
             'Beautiful apartment in the heart of Palermo, very quiet yet close to lively area with bars and restaurants. Maurizio was very helpful and kind, he met me at check in and gave lots of local tips. The flat is very clean and well equipped for a comfortable stay. Highly recommended!',
             '#2E5E32'],
            ['Luyi',        'Francia 🇫🇷',     'Lu', '10', '★★★★★', 'Booking.com', 'Maggio 2025',
             'Everything is perfect in this apartment, you can find everything you need. Perfect location, perfect decoration, equipped kitchen and the 2 beautiful terraces. Very quiet place after visiting chaotic Palermo.',
             '#2E5E32'],
            ['Stuart',      'Regno Unito 🇬🇧', 'S',  '10', '★★★★★', 'Booking.com', 'Aprile 2025',
             'This is a great apartment right in the heart of Palermo, about 10 minutes walk to both the stylish Marina area and the historic Cathedral. Maurizio was a great host, very informative and helpful. The apartment was well air-conditioned and has 2 balcony/terrace areas. The surrounding area was buzzing with lots of lively little bars and cafés.',
             '#2E5E32'],
            ['Ariane',      'Germania 🇩🇪',    'Ar', '10', '★★★★★', 'Booking.com', 'Settembre 2025',
             'Für uns war alles perfekt ❣️ Absolut tolle Lage, schönes Appartement und süße Terrasse. Dazu noch ist Maurizio der allerbeste Gastgeber. Wir kommen sehr gerne wieder. Vielen Dank für die schöne Zeit 🙏',
             '#2E5E32'],
            ['Stuart',      'Germania 🇩🇪',    'St', '10', '★★★★★', 'Booking.com', 'Ottobre 2024',
             'A beautiful apartment with a balcony at the front and a terrace at the back. Great kitchen with high quality equipment. Retro bathroom with plenty of space. So many lovely details which you don\'t usually find in a holiday apartment. Best location to go into town in 10 minutes by foot.',
             '#2E5E32'],
            ['Ross',        'Regno Unito 🇬🇧', 'Ro', '10', '★★★★★', 'Booking.com', 'Ottobre 2024',
             'The apartment was wonderful, just like the kind and generous host who clearly takes great pride in both the apartment and in ensuring that guests have a great time in Palermo. The apartment is extremely well equipped. The location is fantastic, a great base from which to explore Palermo and beyond.',
             '#2E5E32'],
            ['Corinna',     'Germania 🇩🇪',    'Co', '10', '★★★★★', 'Booking.com', 'Settembre 2024',
             'Perfekte Lage, sehr ruhig und trotzdem zentral zu Sehenswürdigkeiten, netten Restaurants und Bars gelegen. Zwei Terrassen laden zu gemütlichen Abenden ein. Die Ausstattung der Wohnung lässt keine Wünsche offen und Maurizio als Host ist super sympathisch und hält jede Menge Insider Tipps bereit. Wir kommen auf jeden Fall wieder.',
             '#2E5E32'],
            ['Sebastien',   'Francia 🇫🇷',     'Se', '10', '★★★★★', 'Booking.com', 'Settembre 2024',
             'L\'appartement est très mignon, bien équipé avec une jolie petite terrasse. L\'emplacement est génial pour visiter. Le propriétaire est très accueillant, il parle le français. Il nous a renseigné sur plein de choses. Nous sommes contents de notre séjour.',
             '#2E5E32'],
            ['Orla',        'Regno Unito 🇬🇧', 'Or', '10', '★★★★★', 'Booking.com', 'Giugno 2024',
             'Fantastic apartment in a great area in Palermo. This well equipped apartment has everything you need to enjoy your stay.',
             '#2E5E32'],
            ['Krzysztof',   'Polonia 🇵🇱',     'Kr', '10', '★★★★★', 'Booking.com', 'Giugno 2024',
             'Maurizio is a spectacular host — he was responsive, adjusted to our arrival time and had a ton of recommendations and tips. The apartment has a lot of character and is perfectly located right in the historical center. We loved eating our breakfasts outside on the terrace!',
             '#2E5E32'],
            ['Regina',      'Germania 🇩🇪',    'Re', '10', '★★★★★', 'Booking.com', 'Maggio 2024',
             'Maurizio offers the cutest apartment in the Kalsa neighbourhood (best place to stay in Palermo), where you can find plenty of bars, cafes and restaurants — 5 min walk and you\'re entering the touristic area. The apartment itself was so cute and has a nice rooftop terrace. Would definitely stay here again.',
             '#2E5E32'],
            ['Marlene',     'Germania 🇩🇪',    'Ml', '10', '★★★★★', 'Booking.com', 'Aprile 2024',
             'Nicht zu viel versprochen! Die Wohnung ist in einem ziemlich schönen Viertel von Palermo mit zahlreichen schönen Cafés und Bars. Außerdem war der Host Maurizio sehr bemüht uns den Aufenthalt so angenehm wie möglich zu gestalten.',
             '#2E5E32'],
            ['Monique',     'Germania 🇩🇪',    'Mo', '10', '★★★★★', 'Booking.com', 'Giugno 2024',
             'Eine Wohnung in der man sich einfach nur wohl fühlen kann. Super schöner Balkon. Super Lage in unmittelbarer Nähe zu tollen Bars und Restaurants. Und ein super zuvorkommender Host mit tollen Tipps.',
             '#2E5E32'],
            ['Thibault',    'Francia 🇫🇷',     'Th', '10', '★★★★★', 'Booking.com', 'Aprile 2024',
             'Une localisation exceptionnelle et un hôte parfait qui rend tout facile.',
             '#2E5E32'],
            ['Tomas',       'Polonia 🇵🇱',     'To', '10', '★★★★★', 'Booking.com', 'Aprile 2024',
             'Fajny, komfortowy apartament, wyposażony we wszystko co potrzeba. Dobre miejsce do zamieszkania w Palermo, aby na nogach poznać klimat starego miasta. Bardzo miły gospodarz.',
             '#2E5E32'],
            ['Narciso',     'Spagna 🇪🇸',      'Na', '10', '★★★★★', 'Booking.com', 'Aprile 2024',
             'Todo perfecto, la zona me gustó mucho, super céntrico, el apartamento impecable. Mejor que en las fotos. Y un 10 al anfitrión, lo recomiendo totalmente.',
             '#2E5E32'],
            ['Julie',       'Regno Unito 🇬🇧', 'Ju', '10', '★★★★★', 'Booking.com', 'Ottobre 2023',
             'We stayed for 10 days at Maurizio\'s apartment and it felt like a home from home. He met us at check in and gave us lots of useful tips. The accommodation had plenty of personality, the bed was comfortable, the shower was great. Having a balcony and terrace to relax on was a bonus. One of the best city apartments we\'ve stayed in.',
             '#2E5E32'],
            ['Kris',        'Belgio 🇧🇪',      'Ks', '10', '★★★★★', 'Booking.com', 'Settembre 2023',
             'We loved staying at My House, dead in the center of Palermo yet in a relatively quiet and peaceful neighborhood. The charming host Maurizio was very welcoming and gave us loads of great advice. What we appreciated immensely were the quality of the beds and how well the apartment was equipped.',
             '#2E5E32'],
            ['Matus',       'Slovacchia 🇸🇰',  'Mt', '10', '★★★★★', 'Booking.com', 'Settembre 2023',
             'We had an amazing time at Maurizio\'s apartment. It has an amazing authentic cozy atmosphere with everything you need for your pleasant stay. We recommend it 100%, especially for its great location in historic Palermo city center.',
             '#2E5E32'],
            ['Caroline',    'Irlanda 🇮🇪',     'C',  '10', '★★★★★', 'Booking.com', 'Settembre 2023',
             'Beautiful, cosy and very comfortable apartment in the best location in Palermo. Located in the beautiful Kalsa area, near lovely restaurants and bars. Maurizio is a fantastic host and very kind person who gave us great recommendations. Would definitely recommend and hope to be back.',
             '#2E5E32'],
            ['Garrett',     'Stati Uniti 🇺🇸', 'Ga', '10', '★★★★★', 'Booking.com', 'Settembre 2023',
             'My House 44 was phenomenal! Cozy, comfortable, and centrally located. Very centrally located and yet on a quiet side street. A great place to stay!',
             '#2E5E32'],
            ['Mateusz',     'Polonia 🇵🇱',     'Mz', '10', '★★★★★', 'Booking.com', 'Luglio 2023',
             'Everything was perfect 😊 Maurizio is a fantastic host, and the apartment is wonderful. Hope to come back soon 😊',
             '#2E5E32'],
            ['Julita',      'Polonia 🇵🇱',     'Jl', '10', '★★★★★', 'Booking.com', 'Maggio 2023',
             'Przesympatyczny gospodarz, który przywitał nas w mieszkaniu i udzielił pomocnych wskazówek. Apartament wyposażony we wszystko co potrzebne, by poczuć się jak w domu. Rewelacyjna lokalizacja — blisko do najważniejszych atrakcji, można zwiedzać Palermo spacerem.',
             '#2E5E32'],
            ['Tatyana',     'Stati Uniti 🇺🇸', 'Ta', '10', '★★★★★', 'Booking.com', 'Aprile 2023',
             'Located within walking distance to all attractions, small, clean apartment with a nice terrace. Maurizio met us in the apartment, provided us with the city map and explained all attractions in detail.',
             '#2E5E32'],
            ['Fabian',      'Svizzera 🇨🇭',    'Fa', '10', '★★★★★', 'Booking.com', 'Ottobre 2025',
             'Cool area, central but quiet, you feel like a local!',
             '#2E5E32'],

            // ════════════════════════════════════════
            //  SCORE 10 — Airbnb ★★★★★
            // ════════════════════════════════════════
            ['Traci',       'Ohio, USA 🇺🇸',   'T',  '10', '★★★★★', 'Airbnb', 'Settembre 2025',
             'L\'alloggio di Maurizio è accogliente e super carino. Era molto pulito e ordinato. Era come essere a casa propria. Ti fa sentire a casa salutandoti e facendoti fare un giro dell\'alloggio. Ha dato ottimi consigli su ristoranti e luoghi da vedere. Soggiornerò sicuramente a casa di Mau quando tornerò a Palermo.',
             '#2E5E32'],
            ['Violette',    'Airbnb',           'VM', '10', '★★★★★', 'Airbnb', 'Settembre 2025',
             'Soggiorno fantastico in due, ci è piaciuto molto stare a casa di Maurizio che ci ha accolto come regine. Abbiamo trovato la posizione davvero fantastica e l\'appartamento molto bene per riposare durante il giorno e la sera. Terrazza molto bella! Grazie Maurizio 🙏',
             '#2E5E32'],
            ['Linda',       'Airbnb',           'Li', '10', '★★★★★', 'Airbnb', 'Settembre 2025',
             'La posizione dell\'appartamento ci è piaciuta particolarmente — nel centro storico, ma nella parte meno turistica. Molti ottimi ristoranti e bar nelle immediate vicinanze. La comunicazione con Maurizio è stata fantastica e i suoi consigli per Palermo molto utili.',
             '#2E5E32'],
            ['Angélique',   'Airbnb',           'A',  '10', '★★★★★', 'Airbnb', 'Agosto 2025',
             'L\'appartamento di Maurizio è situato in posizione ideale. Si può passeggiare in tutte le stradine del centro. Vicino ai mezzi di trasporto per muoversi a Cefalù, Mondello. Un grande grazie a Maurizio per tutti i suoi consigli e la splendida decorazione dell\'appartamento. Potete andarci a occhi chiusi.',
             '#2E5E32'],
            ['Stephanie',   'Airbnb',           'Sf', '10', '★★★★★', 'Airbnb', 'Ottobre 2024',
             'Maurizio è stato molto cordiale e disponibile, l\'appartamento è molto pulito e facile da raggiungere. Mi sono sentita molto sicura durante il mio soggiorno come donna che viaggia da sola. Maurizio ha offerto molti consigli utili. Ho apprezzato l\'attenzione ai dettagli, le opere d\'arte e il patio. Ci tornerei senz\'altro.',
             '#2E5E32'],
            ['Gilles',      'Airbnb',           'Gi', '10', '★★★★★', 'Airbnb', 'Agosto 2024',
             'Soggiorno molto piacevole a Palermo. Il quartiere è perfetto, con molti luoghi di interesse culturale nelle vicinanze, buoni ristoranti, vicino al porto e alla stazione ferroviaria. L\'alloggio era perfetto, identico alla descrizione. Il nostro ospite Maurizio è particolarmente cordiale e il suo francese impeccabile.',
             '#2E5E32'],
            ['Manuela',     'Airbnb',           'Mn', '10', '★★★★★', 'Airbnb', 'Luglio 2024',
             'Non avrei mai pensato di poter trascorrere una vacanza così bella da solo. Questo alloggio ha contribuito molto perché è semplicemente molto accogliente, bello e offre un\'atmosfera di benessere. La posizione è semplicemente perfetta perché si può raggiungere tutto a piedi. Mi piacerebbe sicuramente tornare.',
             '#2E5E32'],
            ['Georgina',    'Airbnb',           'Go', '10', '★★★★★', 'Airbnb', 'Giugno 2024',
             'Il nostro soggiorno è stato meraviglioso. L\'appartamento è pulito, accogliente, confortevole e dispone sia di balcone che di terrazza sul tetto. È anche in un\'ottima posizione per godersi il meglio di Palermo. Maurizio è un host perfetto, estremamente disponibile e molto cordiale! Consigliamo questo soggiorno a chiunque 😊',
             '#2E5E32'],
            ['Jennifer',    'Montreal 🇨🇦',     'Je', '10', '★★★★★', 'Airbnb', 'Giugno 2024',
             'Abbiamo trascorso un soggiorno fantastico! Maurizio è stato così accogliente e disponibile! Questo alloggio è così pulito! Ci ha anche accolto con una bottiglia di vino! Lo consiglio vivamente! È anche molto ben posizionato.',
             '#2E5E32'],
            ['Audrey',      'Airbnb',           'Au', '10', '★★★★★', 'Airbnb', 'Luglio 2024',
             'Lo consiglio ad occhi chiusi! Maurizio è stato semplicemente fantastico, premuroso e molto accogliente. L\'alloggio è situato in posizione ideale e arredato con molto gusto.',
             '#2E5E32'],
            ['Gustavo',     'Buenos Aires 🇦🇷', 'Gu', '10', '★★★★★', 'Airbnb', 'Giugno 2024',
             'Appartamento impeccabile, ottimamente attrezzato, belle decorazioni, vicino a tutto, molto tranquillo. Maurizio è un genio totale! Da tornare e da consigliare sempre.',
             '#2E5E32'],
            ['Michelle',    'Miami, USA 🇺🇸',   'Mi', '10', '★★★★★', 'Airbnb', 'Giugno 2024',
             'HOST PERFETTO! LOFT FANTASTICO! OTTIMA POSIZIONE! Come donna che viaggia da sola, Maurizio mi ha fatto sentire così a casa e al sicuro. Loft dal design accattivante con arredi di fascia alta. Letto molto confortevole, balcone e terrazza. Maurizio si è fatto in quattro e ha dato ottimi consigli su dove visitare. Non volevo andarmene!',
             '#2E5E32'],
            ['Jan',         'Airbnb',           'Jn', '10', '★★★★★', 'Airbnb', 'Aprile 2024',
             'Tutto il meglio: appartamento, posizione, host. Non ho nulla da criticare!',
             '#2E5E32'],
            ['Tifenn',      'Airbnb',           'Ti', '10', '★★★★★', 'Airbnb', 'Luglio 2023',
             'Ho trascorso un ottimo soggiorno nell\'appartamento di Maurizio. L\'appartamento è molto spazioso, confortevole e soprattutto molto pulito. La cucina è molto ben attrezzata. Ho soggiornato una settimana per il telelavoro e il wifi funzionava molto bene. Molto ben posizionato nel pieno centro di Palermo. Maurizio è un host fantastico.',
             '#2E5E32'],
            ['Paola',       'Airbnb',           'Pa', '10', '★★★★★', 'Airbnb', 'Ottobre 2023',
             'Casa molto carina, molto più calda e accogliente di una classica casa vacanze. Consigliata per la posizione, vicina a tutto e immersa nei vicoli della Kalsa, ma anche molto carina e attrezzata. Ci tornerei senza dubbio.',
             '#2E5E32'],
            ['Susana',      'Airbnb',           'Su', '10', '★★★★★', 'Airbnb', 'Agosto 2023',
             'La casa di Mau è molto pulita e ordinata, dotata di tutto e l\'arredamento è bellissimo. Maurizio è sempre stato molto gentile e disponibile. Il letto è molto comodo, il wifi è molto veloce e l\'aria condizionata funziona alla grande. Posizione perfetta a soli 10 minuti a piedi dai principali interessi turistici.',
             '#2E5E32'],
            ['Jasmyn',      'Miami, USA 🇺🇸',   'Js', '10', '★★★★★', 'Airbnb', 'Giugno 2023',
             'Ho trascorso un soggiorno incantevole da Mau. Il posto era così confortevole e accogliente, e mi sentivo davvero un siciliano dall\'inizio alla fine. L\'appartamento è in posizione centrale ma tranquillo, a circa 2 isolati dal trambusto intenso. Mau è stato un host meraviglioso che ha dato consigli incredibili per la mia visita.',
             '#2E5E32'],
            ['Stefano',     'Airbnb',           'Sf', '10', '★★★★★', 'Airbnb', 'Settembre 2023',
             'Maurizio è un ottimo host, la casa è pulita e in una posizione super, perfetta per coppie.',
             '#2E5E32'],
            ['Lucie',       'Airbnb',           'Lc', '10', '★★★★★', 'Airbnb', 'Agosto 2023',
             'Consiglio vivamente questo appartamento, tutto era perfetto. Mi è piaciuto avere un balcone privato e un terrazzo. Maurizio è una persona molto gentile e disponibile, mi ha dato consigli utili su dove andare e dove mangiare. Quando tornerò a Palermo soggiornerò sicuramente nello stesso posto.',
             '#2E5E32'],
            ['Najib',       'Cile 🇨🇱',         'Nj', '10', '★★★★★', 'Airbnb', 'Settembre 2023',
             'Uno dei posti migliori in cui stare, di sempre. Si noti che è dotato di due balconi. Il posto ha una sua personalità ed è molto ben tenuto. Non sono mai stato in un posto così.',
             '#2E5E32'],
            ['Bas',         'Airbnb',           'Bs', '10', '★★★★★', 'Airbnb', 'Ottobre 2023',
             'Grazioso appartamento nel miglior quartiere di Palermo.',
             '#2E5E32'],
            ['Suzanne',     'Montreal 🇨🇦',     'Sz', '10', '★★★★★', 'Airbnb', 'Luglio 2022',
             'Grazie a Maurizio che è stato un ospite esemplare, accogliente, amichevole, simpaticissimo! L\'appartamento è molto carino, decorato con gusto, pulito, confortevole, sicuro e tranquillo. Si trova in una bellissima zona del centro storico, vivace e creativa, a due passi dei posti da vedere.',
             '#2E5E32'],
            ['Jonas',       'Airbnb',           'Jo', '10', '★★★★★', 'Airbnb', 'Luglio 2022',
             'Maurizio è un host eccezionale, amichevole, entusiasta e fa davvero di tutto per assicurarti che tu ti senta a tuo agio. Ci è piaciuto molto soggiornare qui. Posso davvero consigliare My House 44 a chiunque, ha tutti i servizi di cui hai bisogno ed è in una posizione ottima.',
             '#2E5E32'],
            ['Val',         'Airbnb',           'Vl', '10', '★★★★★', 'Airbnb', 'Ottobre 2022',
             'La casa di Mau era fantastica! Ottima posizione e atmosfera dell\'appartamento. Maurizio e Tiziana sono stati host meravigliosi che si sono assicurati che mi trovassi bene. Grazie!!!',
             '#2E5E32'],
            ['Ruth',        'Airbnb',           'Ru', '10', '★★★★★', 'Airbnb', 'Giugno 2022',
             'Maurizio è un ottimo host! Ha consigliato tantissimi posti carini da visitare ed è stato molto utile durante tutto il nostro viaggio. L\'appartamento è fantastico e anche la posizione è molto bella, lo consiglio vivamente!',
             '#2E5E32'],
            ['Yvonne',      'Airbnb',           'Yv', '10', '★★★★★', 'Airbnb', 'Maggio 2022',
             'Maurizio è un fantastico host con ottimi consigli su cosa vedere e la cucina. L\'appartamento è perfettamente situato e arredato con cura. Ci sono piaciuti la terrazza sul cortile e il balcone verso la piccola strada. Sceglieremmo questo appartamento ancora e ancora.',
             '#2E5E32'],
            ['Judith',      'Airbnb',           'Jd', '10', '★★★★★', 'Airbnb', 'Maggio 2022',
             'Grazioso e accogliente appartamento molto pulito e cucina completamente attrezzata. La terrazza panoramica è un luogo perfetto per rilassarsi o cenare. Maurizio ha avuto ottimi consigli e ha risposto velocemente alle domande — un formidabile host! L\'appartamento si trova nella zona più trendy di Palermo.',
             '#2E5E32'],
            ['Benoît',      'Airbnb',           'Bn', '10', '★★★★★', 'Airbnb', 'Marzo 2022',
             'Maurizio e Davide sono host eccellenti. L\'appartamento è incantevole, e in un\'ottima posizione vicino alla stazione ferroviaria, al porto turistico e al centro storico.',
             '#2E5E32'],
            ['Sean',        'Airbnb',           'Sn', '10', '★★★★★', 'Airbnb', 'Aprile 2022',
             'Un appartamento molto centrale e accogliente a Palermo, con un bel terrazzo e una cucina ben attrezzata. Maurizio è un padrone di casa molto gentile, e mi ha anche portato una colomba, una torta di Pasqua tradizionale italiana! Ci tornerei sicuramente, grazie Maurizio!',
             '#2E5E32'],
            ['Sara',        'Airbnb',           'Sr', '10', '★★★★★', 'Airbnb', 'Marzo 2022',
             'Appartamento super carino con un tocco molto personale! La posizione è ottima e si trova nel cuore della vita notturna di Palermo. Maurizio è un ottimo host che offre molti buoni consigli.',
             '#2E5E32'],
            ['Erez',        'Airbnb',           'Er', '10', '★★★★★', 'Airbnb', 'Marzo 2022',
             'Maurizio è l\'host migliore di sempre. Molto gentile, molto alla mano, molto disponibile. L\'appartamento è accogliente e molto confortevole, il Wi-Fi è eccellente e la cucina è fantastica e dotata di tutto il necessario.',
             '#2E5E32'],
            ['Michaela',    'Airbnb',           'Mc', '10', '★★★★★', 'Airbnb', 'Febbraio 2022',
             'Grazioso appartamento situato in una zona super bella, a 5 minuti a piedi dalla stazione ferroviaria e dai Quattro Canti. L\'appartamento è arredato con gusto, pulitissimo, ben attrezzato e dispone di una terrazza che si affaccia sul cortile interno. L\'accoglienza fatta da Maurizio è al top. Torneremo con grande piacere!',
             '#2E5E32'],
            ['Veronica',    'Airbnb',           'Ve', '10', '★★★★★', 'Airbnb', 'Febbraio 2022',
             'Maurizio è uno splendido host, ci ha accolte e ci ha dato preziosi consigli per visitare la città. La casa è molto accogliente, estremamente pulita e la posizione centrale permette di visitare a piedi tutto il centro storico. Un soggiorno che consiglierei.',
             '#2E5E32'],
            ['Wolfgang',    'Airbnb',           'Wf', '10', '★★★★★', 'Airbnb', 'Dicembre 2021',
             'Maurizio è un ottimo host ed è sempre a disposizione con consigli e assistenza. L\'appartamento è arredato in modo molto accogliente e situato in una zona centralissima e tranquilla.',
             '#2E5E32'],
            ['Stuart',      'Airbnb',           'S',  '10', '★★★★★', 'Airbnb', 'Novembre 2021',
             'Maurizio è stato fantastico: molto comprensivo e sempre disponibile. Appartamento e posizione erano entrambi perfetti: la base ideale per esplorare la città.',
             '#2E5E32'],
            ['Tomasz',      'Airbnb',           'Tm', '10', '★★★★★', 'Airbnb', 'Settembre 2021',
             'Maurizio ci ha accolto calorosamente nell\'appartamento, ci ha dato consigli per la zona e siamo stati sempre benissimo. L\'appartamento era confortevole, pulito, accogliente e molto ben attrezzato! La posizione è ottima e tutto è comodo da raggiungere a piedi.',
             '#2E5E32'],
            ['Klára',       'Airbnb',           'Kl', '10', '★★★★★', 'Airbnb', 'Settembre 2021',
             'Maurizio e Davide sono host fantastici. Ci hanno suggerito un sacco di posti fantastici da visitare o per andare a cena fuori. Ti aiutano in tutto ciò che possono e sono anche molto organizzati.',
             '#2E5E32'],
            ['Sagi',        'Airbnb',           'Sg', '10', '★★★★★', 'Airbnb', 'Giugno 2021',
             'La posizione è incredibile e l\'appartamento in sé sembra ancora meglio nella vita reale! È tranquillo, ci sono bar e ristoranti proprio accanto, e il lungomare è anche molto vicino — un vantaggio per una passeggiata. Consiglio vivamente questo appartamento.',
             '#2E5E32'],
            ['Julien',      'Airbnb',           'Jl', '10', '★★★★★', 'Airbnb', 'Luglio 2021',
             'Il nostro soggiorno è stato perfetto: la posizione, l\'ospitalità di Maurizio, la pulizia dell\'appartamento, la sua reattività. In breve, lo consigliamo senza esitazione! Grazie ancora!',
             '#2E5E32'],
            ['Eva',         'Airbnb',           'Ev', '10', '★★★★★', 'Airbnb', 'Luglio 2021',
             'My house 44 è un posto meraviglioso e accogliente nel cuore di Palermo. Maurizio è un host attento e reattivo. L\'appartamento è incantevole e confortevole e ha tutto il necessario, la terrazza è un grande vantaggio.',
             '#2E5E32'],
            ['Martina',     'Airbnb',           'Ma', '10', '★★★★★', 'Airbnb', 'Luglio 2021',
             'La casetta molto accogliente e Maurizio molto disponibile. Ci siamo trovati molto bene, consigliamo di alloggiare in questo posto 😊',
             '#2E5E32'],
            ['Patrik',      'Berna 🇨🇭',        'Pk', '10', '★★★★★', 'Airbnb', 'Luglio 2021',
             'Maurice ha arredato il suo appartamento con molto amore e stile, ci sono anche piccole cose che sono molto apprezzate dai viaggiatori. La disponibilità e i consigli personali erano fantastici e generosi.',
             '#2E5E32'],
            ['Zélie',       'Airbnb',           'Zl', '10', '★★★★★', 'Airbnb', 'Agosto 2021',
             'Airbnb fantastico! Ottima posizione e l\'appartamento è piacevole da vivere. Maurizio è disponibile e gentilissimo. Niente da dire, lo consiglio!!',
             '#2E5E32'],
            ['Meve',        'Airbnb',           'Mv', '10', '★★★★★', 'Airbnb', 'Agosto 2021',
             'Bell\'appartamento. Splendida posizione. L\'host è molto facile da contattare e disponibile.',
             '#2E5E32'],
            ['Emmanuelle',  'Airbnb',           'Em', '10', '★★★★★', 'Airbnb', 'Maggio 2021',
             'Grazioso appartamento arredato con gusto in pieno centro storico di Palermo. Maurizio è un host attento, cordiale e disponibile. Lo consiglio!',
             '#2E5E32'],
            ['Amy',         'Airbnb',           'Am', '10', '★★★★★', 'Airbnb', 'Ottobre 2020',
             'Un bellissimo appartamento accogliente con una meravigliosa piccola terrazza privata. In posizione perfetta per godersi il cuore di Palermo, ma in una strada più tranquilla. Sono stata accolta da Maurizio e Davide che sono stati così accoglienti con i loro numerosi consigli. Ho prolungato il mio viaggio. Anche il materasso è MOLTO comodo.',
             '#2E5E32'],
            ['Celia',       'Airbnb',           'Ce', '10', '★★★★★', 'Airbnb', 'Ottobre 2020',
             'L\'appartamento si trova centrico, perfetto per raggiungere tutti i posti importanti della città. Maurizio mi ha ricevuto con molta ospitalità anche se sono arrivata veramente tardi. Ripeterei sicuro in questo Airbnb.',
             '#2E5E32'],
            ['David',       'Airbnb',           'Dv', '10', '★★★★★', 'Airbnb', 'Settembre 2020',
             'Un appartamento incantevole e caratteristico, molto ben arredato, perfettamente pulito e in una posizione ottima. Maurizio è stato molto accomodante e ha avuto alcuni ottimi suggerimenti su luoghi da visitare e mangiare. Starei sicuramente di nuovo qui.',
             '#2E5E32'],
            ['Alexander',   'Denver, USA 🇺🇸',  'Al', '10', '★★★★★', 'Airbnb', 'Settembre 2020',
             'L\'alloggio di Maurizio è il miglior alloggio Airbnb in cui abbia mai soggiornato. Tutto era elegante, pulito, molto più grande di quanto immaginassi. I 2 grandi balconi sono incredibili. La posizione era imbattibile: a 2 minuti da ottimi ristoranti, bar e tutti i siti importanti, in una tranquilla strada secondaria.',
             '#2E5E32'],
            ['Aleksa',      'Airbnb',           'Ak', '10', '★★★★★', 'Airbnb', 'Agosto 2020',
             'Splendido appartamento nel centro storico di Palermo. Le principali attrazioni sono raggiungibili a piedi e Maurizio è un host meraviglioso! Lo consiglio vivamente!',
             '#2E5E32'],
            ['Anastasia',   'Airbnb',           'As', '10', '★★★★★', 'Airbnb', 'Febbraio 2020',
             'L\'appartamento è ancora meglio dal vivo! La cosa migliore (oltre alla terrazza dove puoi goderti il sole) è la posizione: tutto è raggiungibile a piedi ed è ancora tranquillo. Maurizio è un super host, ci ha fornito informazioni utili. Merita sicuramente un soggiorno!',
             '#2E5E32'],
            ['Jo',          'Airbnb',           'Jo', '10', '★★★★★', 'Airbnb', 'Febbraio 2020',
             'Hai sentito parlare dell\'ospitalità siciliana: Maurizio ne è la personificazione. Questo appartamento è ancora più bello delle foto. La posizione è fantastica, centrale ma tranquilla e accogliente. Tutti gli arredi e le attrezzature sono di ottima qualità ed eleganti. Ho davvero apprezzato i miei 10 giorni nell\'appartamento di Maurizio.',
             '#2E5E32'],
            ['Shonnie',     'New York, USA 🇺🇸', 'Sh', '10', '★★★★★', 'Airbnb', 'Dicembre 2019',
             'La casa di Maurizio è una vera perla. La casa è ancora più bella di quanto non sia nelle foto, con tanti tocchi premurosi e un balcone incredibile. Maurizio ci ha dato un sacco di ottimi consigli locali.',
             '#2E5E32'],
            ['Kaushik',     'Airbnb',           'Ka', '10', '★★★★★', 'Airbnb', 'Novembre 2019',
             'La posizione dell\'alloggio è perfetta e l\'appartamento era ben attrezzato con tutto. Maurizio è un host fantastico. All\'inizio ci ha dato un caloroso benvenuto e informazioni sui luoghi interessanti da visitare e da mangiare. Seguendo i suoi consigli abbiamo passato un soggiorno splendido.',
             '#2E5E32'],
            ['Roy',         'Airbnb',           'Ry', '10', '★★★★★', 'Airbnb', 'Novembre 2019',
             'Posto molto bello, pulito, stravagante, bello e centrale! Gli host sono semplicemente fantastici. Lo consiglio a tutti, inclusa mia madre. Semplicemente il migliore!',
             '#2E5E32'],
            ['Hagen',       'Airbnb',           'Hg', '10', '★★★★★', 'Airbnb', 'Ottobre 2019',
             'La location è fantastica, super centrale, ma davvero abbastanza silenziosa di notte. Il posto era pulito e decorato con tanto amore e attenzione ai dettagli. Maurizio era super cordiale ed era sempre disponibile quando avevamo una domanda. Ci siamo davvero sentiti come a casa.',
             '#2E5E32'],
            ['Charles',     'Airbnb',           'Ch', '10', '★★★★★', 'Airbnb', 'Ottobre 2019',
             'Appartamento molto elegante, splendidamente arredato. Maurizio ha comunicato rapidamente e si è adattato al nostro treno cancellato. Ci ha accolto in Piazza Rivoluzione e ci ha lasciato dei bei dolci. Un\'esperienza molto buona!',
             '#2E5E32'],
            ['Marcel',      'Airbnb',           'Mc', '10', '★★★★★', 'Airbnb', 'Ottobre 2019',
             'Non troverai niente di meglio a Palermo. A 7 minuti a piedi dalla stazione ferroviaria, appena fuori troverai ristoranti, bar e panetterie. L\'appartamento è arredato con gusto e molto completo. E per quanto riguarda Maurizio: è l\'uomo più gentile che troverai a Palermo.',
             '#2E5E32'],
            ['Sybil',       'Airbnb',           'Sy', '10', '★★★★★', 'Airbnb', 'Ottobre 2019',
             'Il duplex di Maurizio è semplicemente perfetto! È un host reattivo, con buoni consigli e premuroso. L\'alloggio è perfettamente pulito, molto ben attrezzato e funzionale. Lo consiglio vivamente!',
             '#2E5E32'],
            ['Bea',         'Airbnb',           'Be', '10', '★★★★★', 'Airbnb', 'Dicembre 2019',
             'L\'appartamento è molto bello e amorevolmente presentato con uno sguardo per i dettagli. Tutto è molto curato e la cucina è ampiamente attrezzata. Assolutamente da sogno è la piccola terrazza. Maurizio mi ha accolto personalmente e mi ha dato subito numerosi consigli. Un perfetto padrone di casa!',
             '#2E5E32'],
            ['Carlo',       'Airbnb',           'Ca', '10', '★★★★★', 'Airbnb', 'Settembre 2019',
             'Maurizio è stato un host splendido e disponibile, capace di comunicare da subito tutto il calore della sua città. L\'appartamento è collocato nel centro storico di Palermo, i colori caldi lo rendono ancora più accogliente. Pulito e curato in ogni dettaglio, è perfetto per un weekend o per un periodo più lungo.',
             '#2E5E32'],
            ['Giovanni',    'Airbnb',           'Gv', '10', '★★★★★', 'Airbnb', 'Settembre 2019',
             'Consigliatissima!! Posizione strategica in pieno centro storico, pulizia ineccepibile, casa curatissima, ancora più bella che nelle foto! Host davvero speciale! Seguite i suoi consigli!!',
             '#2E5E32'],
            ['Roberto',     'Airbnb',           'Rb', '10', '★★★★★', 'Airbnb', 'Settembre 2019',
             'Maurizio è il top! L\'appartamento rispecchia a pieno tutta la passione e la professionalità che mette nell\'accogliere i suoi ospiti. Il quartiere e la posizione dell\'appartamento è l\'ideale per visitare il centro storico di Palermo.',
             '#2E5E32'],
            ['Paolo',       'Airbnb',           'Po', '10', '★★★★★', 'Airbnb', 'Settembre 2019',
             'La posizione è strategica per visitare e vivere la città al meglio. La cortesia e l\'ospitalità di Maurizio sono state componenti fondamentali per rilassarsi e godere delle bellezze della città. Appartamento completo e adeguato alle nostre esigenze. Consigliatissimo.',
             '#2E5E32'],
            ['Catherine',   'Airbnb',           'Ct', '10', '★★★★★', 'Airbnb', 'Luglio 2019',
             'Mauricio ci ha accolto molto bene nel suo duplex che è molto pulito, ben attrezzato, ben posizionato e in una strada tranquilla vicino a tutti i monumenti da visitare. Ci ha dato un sacco di buoni indirizzi per visitare e andare a mangiare. Consiglio vivamente questo appartamento.',
             '#2E5E32'],
            ['Guido',       'Airbnb',           'Gu', '10', '★★★★★', 'Airbnb', 'Giugno 2019',
             'Appartamento nel cuore storico di Palermo, molto ben servito per la vicinanza dei mezzi pubblici, spazioso, quieto, curato, pulitissimo. L\'accoglienza davvero speciale ha contribuito a rendere splendida la nostra vacanza. Una sorpresa è stata la terrazza interna, spazio ideale per l\'aperitivo serale.',
             '#2E5E32'],
            ['Elsa',        'Airbnb',           'El', '10', '★★★★★', 'Airbnb', 'Agosto 2019',
             'Appartamento pulito e ben attrezzato, situato nella bellissima zona della Kalsa, a 10 minuti dalla stazione ferroviaria. Host reattivi e molto ospitali.',
             '#2E5E32'],
            ['Mara',        'Airbnb',           'Mr', '10', '★★★★★', 'Airbnb', 'Agosto 2019',
             'La location, molto ben arredata, si trova in una posizione strategica per visitare Palermo. Maurizio è una persona molto gentile, precisa e disponibile. Se dovessi ritornare a Palermo, sceglierei nuovamente il suo appartamento. Vivamente consigliato.',
             '#2E5E32'],
            ['Danuta',      'Airbnb',           'Da', '10', '★★★★★', 'Airbnb', 'Agosto 2019',
             'Mau-House è un appartamento molto ben arredato, pulito e perfettamente situato al centro di Palermo. Il quartiere è tranquillo e silenzioso. Maurizio è un ottimo host: ci ha accolti di persona, ci ha fornito tanti preziosi consigli per negozi, ristoranti e punti di interesse.',
             '#2E5E32'],
            ['Ray',         'Airbnb',           'Ry', '10', '★★★★★', 'Airbnb', 'Giugno 2019',
             'Fantastico. Ci siamo trovati veramente molto bene. Zona ottima, facile da raggiungere. Proprietari gentilissimi e super disponibili. Torneremo presto.',
             '#2E5E32'],
            ['Marco',       'Airbnb',           'M',  '10', '★★★★★', 'Airbnb', 'Agosto 2019',
             'Maurizio è una persona eccezionale che ha saputo consigliarci al meglio. Grazie anche al suo appartamento abbiamo trascorso una vacanza meravigliosa.',
             '#2E5E32'],
            // ════════════════════════════════════════
            //  SCORE 9 — Booking.com
            // ════════════════════════════════════════
            ['Louise',      'Regno Unito 🇬🇧', 'Lo', '9',  '★★★★★', 'Booking.com', 'Ottobre 2025',
             'We loved everything. Perfect location. The apartment was comfortable, stylish and clean. Maurizio was a great host, giving great recommendations and letting us check in early.',
             '#1C6B50'],
            ['Francesco',   'Italia 🇮🇹',      'F',  '9',  '★★★★★', 'Booking.com', 'Agosto 2024',
             'Struttura molto bella situata nel centro di Palermo che dà la possibilità di visitare comodamente a piedi la città. Perfetta per un soggiorno di coppia!',
             '#1C6B50'],
            ['Ben',         'Stati Uniti 🇺🇸', 'B',  '9',  '★★★★★', 'Booking.com', 'Ottobre 2025',
             'The location was fantastic, everything was easy to walk to and plenty of restaurants right around the corner. The place was great with balconies at both ends and great air flow. Host was super easy to communicate with!!',
             '#1C6B50'],
            ['Kindaa',      'Germania 🇩🇪',    'Ki', '9',  '★★★★★', 'Booking.com', 'Maggio 2024',
             'Die Lage ist top. Die Wohnung ist gut ausgestattet. Maurizio ist sehr nett und hilfsbereit.',
             '#1C6B50'],
            ['Annette',     'Germania 🇩🇪',    'An', '9',  '★★★★★', 'Booking.com', 'Aprile 2023',
             'Sehr gemütlich eingerichtet, für 2 perfekt, zentral gelegen, tolle Dachterrasse, super Tipps vom Gastgeber.',
             '#1C6B50'],

            // ════════════════════════════════════════
            //  SCORE 8 — Airbnb ★★★★☆
            // ════════════════════════════════════════
            ['Sepidar',     'Airbnb',           'Sp', '8',  '★★★★☆', 'Airbnb', 'Agosto 2024',
             'Uno degli host più cordiali e disponibili che abbia mai avuto. Maurizio è stato flessibile e ci ha dato molti ottimi consigli. La posizione è perfetta. Ottimo l\'aria condizionata su entrambi i piani. Il bagno e la mini cucina erano molto puliti e ben funzionanti.',
             '#5A7A32'],
            ['Amy 敏儿',    'Airbnb',           'A',  '8',  '★★★★☆', 'Airbnb', 'Settembre 2023',
             'Posizione privilegiata nel centro storico, un appartamento molto affascinante e pulito con accogliente terrazza. Anche Maurizio è stato molto reattivo! È stato un bel soggiorno.',
             '#5A7A32'],
            ['Keelan',      'San Francisco 🇺🇸','Ke', '8',  '★★★★☆', 'Airbnb', 'Settembre 2021',
             'Ottimo posto, ottima posizione. Maurizio è un ottimo host. Molto cordiale e ospitale. Mi ha fornito molti consigli sulla città. Era anche molto comunicativo. Consiglio questo posto in posizione centrale!',
             '#5A7A32'],
            ['Giulia',      'Airbnb',           'Gl', '8',  '★★★★☆', 'Airbnb', 'Agosto 2020',
             'Soggiornare a My House è stata un\'esperienza fantastica, il posto, la posizione e l\'accoglienza sono stati fantastici! Grazie.',
             '#5A7A32'],

            // ════════════════════════════════════════
            //  SCORE 8 — Booking.com
            // ════════════════════════════════════════
            ['Massimiliano','Italia 🇮🇹',       'Ms', '8',  '★★★★☆', 'Booking.com', 'Gennaio 2024',
             'Appartamento centrale, ben tenuto ed arredato. Comodissimo per raggiungere tutte le principali attrazioni. Pulito e con host simpatico e gentile. Siamo stati bene e lo consigliamo.',
             '#5A7A32'],
            ['Davide',      'Italia 🇮🇹',       'D',  '8',  '★★★★☆', 'Booking.com', 'Maggio 2025',
             'Buona distribuzione degli spazi. Ambiente e bagno molto puliti. Posizione centralissima e ricca di mete di gran interesse. Appartamento completo di tutto.',
             '#5A7A32'],
            ['Michel',      'Francia 🇫🇷',      'Mi', '8',  '★★★★☆', 'Booking.com', 'Maggio 2024',
             'Accueil chaleureux du propriétaire. Demeure de charme.',
             '#5A7A32'],
            ['Sarah',       'Francia 🇫🇷',      'Sa', '8',  '★★★★☆', 'Booking.com', 'Maggio 2023',
             'Maurizio est un hôte charmant qui nous a très bien accueilli, nous a donné de très bons conseils et a facilité notre départ. Le logement est très agréable, très bien équipé et très propre. La petite terrasse à l\'étage est très agréable.',
             '#5A7A32'],
            ['Mauri',       'Italia 🇮🇹',       'Ma', '8',  '★★★★☆', 'Booking.com', 'Luglio 2023',
             'La struttura e la posizione della casa sono ottime. Un soggiorno piacevole nel cuore di Palermo.',
             '#5A7A32'],
        ];
    }
}
